export type Application = {
    _id: string;
    firstName: string;   
    lastName: string;
    nationalId: string;
    email: string;
    teacherId: string;
    phone: string;
    dateOfBirth: Date;
    gender: "Male" | "Female" | "Other";
    maritalStatus: "Single" | "Married" | "Divorced" | "Widowed";
    numberOfDependencies: number;
    workSchool: string;
    position: string;
    monthlySalary: number;
    amountRequested: number;
    repaymentReriod: number;
    bankAccountNumber: string;
    proofOffEmployment: string;
    copyOfNationalId: string;
    loanStatus: "Pending" | "Update required" | "Approved" | "Rejected";
};

export const applications: Application[] = [
    {
        _id: "1",
        firstName: "John",
        lastName: "Doe",
        nationalId: "1234567890123456",
        email: "john.doe@example.com",
        teacherId: "T1001",
        phone: "0712345678",
        dateOfBirth: new Date("1980-05-15"),
        gender: "Male",
        maritalStatus: "Married",
        numberOfDependencies: 2,
        workSchool: "Greenwood High",
        position: "Math Teacher",
        monthlySalary: 3000,
        amountRequested: 15000,
        repaymentReriod: 24,
        bankAccountNumber: "1234567890",
        proofOffEmployment: "https://www.canva.com/p/templates/EAFh7cFx9So-white-and-gold-certificate-of-appreciation/",
        copyOfNationalId: "https://www.canva.com/p/templates/EAFh7cFx9So-white-and-gold-certificate-of-appreciation/",
        loanStatus: "Pending",
    },
    {
        _id: "2",
        firstName: "Jane",
        lastName: "Smith",
        nationalId: "2234567890123456",
        email: "jane.smith@example.com",
        teacherId: "T1002",
        phone: "0712345679",
        dateOfBirth: new Date("1985-11-20"),
        gender: "Female",
        maritalStatus: "Single",
        numberOfDependencies: 0,
        workSchool: "Hillside School",
        position: "English Teacher",
        monthlySalary: 2800,
        amountRequested: 12000,
        repaymentReriod: 18,
        bankAccountNumber: "2234567890",
        proofOffEmployment: "https://www.canva.com/p/templates/EAFh7cFx9So-white-and-gold-certificate-of-appreciation/",
        copyOfNationalId: "https://www.canva.com/p/templates/EAFh7cFx9So-white-and-gold-certificate-of-appreciation/",
        loanStatus: "Approved",
    },
    {
        _id: "3",
        firstName: "Michael",
        lastName: "Johnson",
        nationalId: "3234567890123456",
        email: "michael.johnson@example.com",
        teacherId: "T1003",
        phone: "0712345680",
        dateOfBirth: new Date("1975-02-10"),
        gender: "Male",
        maritalStatus: "Divorced",
        numberOfDependencies: 1,
        workSchool: "Riverdale High",
        position: "Science Teacher",
        monthlySalary: 3200,
        amountRequested: 10000,
        repaymentReriod: 12,
        bankAccountNumber: "3234567890",
        proofOffEmployment: "https://www.canva.com/p/templates/EAFh7cFx9So-white-and-gold-certificate-of-appreciation/",
        copyOfNationalId: "https://www.canva.com/p/templates/EAFh7cFx9So-white-and-gold-certificate-of-appreciation/",
        loanStatus: "Rejected",
    },
    {
        _id: "4",
        firstName: "Emily",
        lastName: "Davis",
        nationalId: "4234567890123456",
        email: "emily.davis@example.com",
        teacherId: "T1004",
        phone: "0712345681",
        dateOfBirth: new Date("1990-07-30"),
        gender: "Female",
        maritalStatus: "Widowed",
        numberOfDependencies: 3,
        workSchool: "Sunset Elementary",
        position: "History Teacher",
        monthlySalary: 2900,
        amountRequested: 16000,
        repaymentReriod: 30,
        bankAccountNumber: "4234567890",
        proofOffEmployment: "https://www.canva.com/p/templates/EAFh7cFx9So-white-and-gold-certificate-of-appreciation/",
        copyOfNationalId: "https://www.canva.com/p/templates/EAFh7cFx9So-white-and-gold-certificate-of-appreciation/",
        loanStatus: "Update required",
    },
    {
        _id: "5",
        firstName: "Robert",
        lastName: "Brown",
        nationalId: "5234567890123456",
        email: "robert.brown@example.com",
        teacherId: "T1005",
        phone: "0712345682",
        dateOfBirth: new Date("1982-03-25"),
        gender: "Male",
        maritalStatus: "Married",
        numberOfDependencies: 4,
        workSchool: "Maplewood High",
        position: "Physics Teacher",
        monthlySalary: 3100,
        amountRequested: 14000,
        repaymentReriod: 20,
        bankAccountNumber: "5234567890",
        proofOffEmployment: "https://www.canva.com/p/templates/EAFh7cFx9So-white-and-gold-certificate-of-appreciation/",
        copyOfNationalId: "https://www.canva.com/p/templates/EAFh7cFx9So-white-and-gold-certificate-of-appreciation/",
        loanStatus: "Pending",
    },
    {
        _id: "6",
        firstName: "Linda",
        lastName: "Miller",
        nationalId: "6234567890123456",
        email: "linda.miller@example.com",
        teacherId: "T1006",
        phone: "0712345683",
        dateOfBirth: new Date("1978-09-18"),
        gender: "Female",
        maritalStatus: "Single",
        numberOfDependencies: 0,
        workSchool: "Oakridge School",
        position: "Chemistry Teacher",
        monthlySalary: 3300,
        amountRequested: 18000,
        repaymentReriod: 36,
        bankAccountNumber: "6234567890",
        proofOffEmployment: "https://www.canva.com/p/templates/EAFh7cFx9So-white-and-gold-certificate-of-appreciation/",
        copyOfNationalId: "https://www.canva.com/p/templates/EAFh7cFx9So-white-and-gold-certificate-of-appreciation/",
        loanStatus: "Approved",
    },
    {
        _id: "7",
        firstName: "David",
        lastName: "Garcia",
        nationalId: "7234567890123456",
        email: "david.garcia@example.com",
        teacherId: "T1007",
        phone: "0712345684",
        dateOfBirth: new Date("1983-12-10"),
        gender: "Male",
        maritalStatus: "Married",
        numberOfDependencies: 2,
        workSchool: "Lakeview High",
        position: "Geography Teacher",
        monthlySalary: 3050,
        amountRequested: 13000,
        repaymentReriod: 15,
        bankAccountNumber: "7234567890",
        proofOffEmployment: "https://www.canva.com/p/templates/EAFh7cFx9So-white-and-gold-certificate-of-appreciation/",
        copyOfNationalId: "https://www.canva.com/p/templates/EAFh7cFx9So-white-and-gold-certificate-of-appreciation/",
        loanStatus: "Rejected",
    },
    {
        _id: "8",
        firstName: "Barbara",
        lastName: "Martinez",
        nationalId: "8234567890123456",
        email: "barbara.martinez@example.com",
        teacherId: "T1008",
        phone: "0712345685",
        dateOfBirth: new Date("1979-04-22"),
        gender: "Female",
        maritalStatus: "Widowed",
        numberOfDependencies: 1,
        workSchool: "Cedarwood Elementary",
        position: "Art Teacher",
        monthlySalary: 2800,
        amountRequested: 12000,
        repaymentReriod: 10,
        bankAccountNumber: "8234567890",
        proofOffEmployment: "https://www.canva.com/p/templates/EAFh7cFx9So-white-and-gold-certificate-of-appreciation/",
        copyOfNationalId: "https://www.canva.com/p/templates/EAFh7cFx9So-white-and-gold-certificate-of-appreciation/",
        loanStatus: "Pending",
   
    },
    {
        _id: "1",
        firstName: "John",
        lastName: "Doe",
        nationalId: "1234567890123456",
        email: "john.doe@example.com",
        teacherId: "T1001",
        phone: "0712345678",
        dateOfBirth: new Date("1980-05-15"),
        gender: "Male",
        maritalStatus: "Married",
        numberOfDependencies: 2,
        workSchool: "Greenwood High",
        position: "Math Teacher",
        monthlySalary: 3000,
        amountRequested: 15000,
        repaymentReriod: 24,
        bankAccountNumber: "1234567890",
        proofOffEmployment: "https://www.canva.com/p/templates/EAFh7cFx9So-white-and-gold-certificate-of-appreciation/",
        copyOfNationalId: "https://www.canva.com/p/templates/EAFh7cFx9So-white-and-gold-certificate-of-appreciation/",
        loanStatus: "Pending",
    },
    {
        _id: "2",
        firstName: "Jane",
        lastName: "Smith",
        nationalId: "2234567890123456",
        email: "jane.smith@example.com",
        teacherId: "T1002",
        phone: "0712345679",
        dateOfBirth: new Date("1985-11-20"),
        gender: "Female",
        maritalStatus: "Single",
        numberOfDependencies: 0,
        workSchool: "Hillside School",
        position: "English Teacher",
        monthlySalary: 2800,
        amountRequested: 12000,
        repaymentReriod: 18,
        bankAccountNumber: "2234567890",
        proofOffEmployment: "https://www.canva.com/p/templates/EAFh7cFx9So-white-and-gold-certificate-of-appreciation/",
        copyOfNationalId: "https://www.canva.com/p/templates/EAFh7cFx9So-white-and-gold-certificate-of-appreciation/",
        loanStatus: "Approved",
    },
    {
        _id: "3",
        firstName: "Michael",
        lastName: "Johnson",
        nationalId: "3234567890123456",
        email: "michael.johnson@example.com",
        teacherId: "T1003",
        phone: "0712345680",
        dateOfBirth: new Date("1975-02-10"),
        gender: "Male",
        maritalStatus: "Divorced",
        numberOfDependencies: 1,
        workSchool: "Riverdale High",
        position: "Science Teacher",
        monthlySalary: 3200,
        amountRequested: 10000,
        repaymentReriod: 12,
        bankAccountNumber: "3234567890",
        proofOffEmployment: "https://www.canva.com/p/templates/EAFh7cFx9So-white-and-gold-certificate-of-appreciation/",
        copyOfNationalId: "https://www.canva.com/p/templates/EAFh7cFx9So-white-and-gold-certificate-of-appreciation/",
        loanStatus: "Rejected",
    },
    {
        _id: "4",
        firstName: "Emily",
        lastName: "Davis",
        nationalId: "4234567890123456",
        email: "emily.davis@example.com",
        teacherId: "T1004",
        phone: "0712345681",
        dateOfBirth: new Date("1990-07-30"),
        gender: "Female",
        maritalStatus: "Widowed",
        numberOfDependencies: 3,
        workSchool: "Sunset Elementary",
        position: "History Teacher",
        monthlySalary: 2900,
        amountRequested: 16000,
        repaymentReriod: 30,
        bankAccountNumber: "4234567890",
        proofOffEmployment: "https://www.canva.com/p/templates/EAFh7cFx9So-white-and-gold-certificate-of-appreciation/",
        copyOfNationalId: "https://www.canva.com/p/templates/EAFh7cFx9So-white-and-gold-certificate-of-appreciation/",
        loanStatus: "Update required",
    },
    {
        _id: "5",
        firstName: "Robert",
        lastName: "Brown",
        nationalId: "5234567890123456",
        email: "robert.brown@example.com",
        teacherId: "T1005",
        phone: "0712345682",
        dateOfBirth: new Date("1982-03-25"),
        gender: "Male",
        maritalStatus: "Married",
        numberOfDependencies: 4,
        workSchool: "Maplewood High",
        position: "Physics Teacher",
        monthlySalary: 3100,
        amountRequested: 14000,
        repaymentReriod: 20,
        bankAccountNumber: "5234567890",
        proofOffEmployment: "https://www.canva.com/p/templates/EAFh7cFx9So-white-and-gold-certificate-of-appreciation/",
        copyOfNationalId: "https://www.canva.com/p/templates/EAFh7cFx9So-white-and-gold-certificate-of-appreciation/",
        loanStatus: "Pending",
    },
    {
        _id: "6",
        firstName: "Linda",
        lastName: "Miller",
        nationalId: "6234567890123456",
        email: "linda.miller@example.com",
        teacherId: "T1006",
        phone: "0712345683",
        dateOfBirth: new Date("1978-09-18"),
        gender: "Female",
        maritalStatus: "Single",
        numberOfDependencies: 0,
        workSchool: "Oakridge School",
        position: "Chemistry Teacher",
        monthlySalary: 3300,
        amountRequested: 18000,
        repaymentReriod: 36,
        bankAccountNumber: "6234567890",
        proofOffEmployment: "https://www.canva.com/p/templates/EAFh7cFx9So-white-and-gold-certificate-of-appreciation/",
        copyOfNationalId: "https://www.canva.com/p/templates/EAFh7cFx9So-white-and-gold-certificate-of-appreciation/",
        loanStatus: "Approved",
    },
    {
        _id: "7",
        firstName: "David",
        lastName: "Garcia",
        nationalId: "7234567890123456",
        email: "david.garcia@example.com",
        teacherId: "T1007",
        phone: "0712345684",
        dateOfBirth: new Date("1983-12-10"),
        gender: "Male",
        maritalStatus: "Married",
        numberOfDependencies: 2,
        workSchool: "Lakeview High",
        position: "Geography Teacher",
        monthlySalary: 3050,
        amountRequested: 13000,
        repaymentReriod: 15,
        bankAccountNumber: "7234567890",
        proofOffEmployment: "https://www.canva.com/p/templates/EAFh7cFx9So-white-and-gold-certificate-of-appreciation/",
        copyOfNationalId: "https://www.canva.com/p/templates/EAFh7cFx9So-white-and-gold-certificate-of-appreciation/",
        loanStatus: "Rejected",
    },
    {
        _id: "8",
        firstName: "Barbara",
        lastName: "Martinez",
        nationalId: "8234567890123456",
        email: "barbara.martinez@example.com",
        teacherId: "T1008",
        phone: "0712345685",
        dateOfBirth: new Date("1979-04-22"),
        gender: "Female",
        maritalStatus: "Widowed",
        numberOfDependencies: 1,
        workSchool: "Cedarwood Elementary",
        position: "Art Teacher",
        monthlySalary: 2800,
        amountRequested: 12000,
        repaymentReriod: 10,
        bankAccountNumber: "8234567890",
        proofOffEmployment: "https://www.canva.com/p/templates/EAFh7cFx9So-white-and-gold-certificate-of-appreciation/",
        copyOfNationalId: "https://www.canva.com/p/templates/EAFh7cFx9So-white-and-gold-certificate-of-appreciation/",
        loanStatus: "Pending",
   
    },
    {
        _id: "1",
        firstName: "John",
        lastName: "Doe",
        nationalId: "1234567890123456",
        email: "john.doe@example.com",
        teacherId: "T1001",
        phone: "0712345678",
        dateOfBirth: new Date("1980-05-15"),
        gender: "Male",
        maritalStatus: "Married",
        numberOfDependencies: 2,
        workSchool: "Greenwood High",
        position: "Math Teacher",
        monthlySalary: 3000,
        amountRequested: 15000,
        repaymentReriod: 24,
        bankAccountNumber: "1234567890",
        proofOffEmployment: "https://www.canva.com/p/templates/EAFh7cFx9So-white-and-gold-certificate-of-appreciation/",
        copyOfNationalId: "https://www.canva.com/p/templates/EAFh7cFx9So-white-and-gold-certificate-of-appreciation/",
        loanStatus: "Pending",
    },
    {
        _id: "2",
        firstName: "Jane",
        lastName: "Smith",
        nationalId: "2234567890123456",
        email: "jane.smith@example.com",
        teacherId: "T1002",
        phone: "0712345679",
        dateOfBirth: new Date("1985-11-20"),
        gender: "Female",
        maritalStatus: "Single",
        numberOfDependencies: 0,
        workSchool: "Hillside School",
        position: "English Teacher",
        monthlySalary: 2800,
        amountRequested: 12000,
        repaymentReriod: 18,
        bankAccountNumber: "2234567890",
        proofOffEmployment: "https://www.canva.com/p/templates/EAFh7cFx9So-white-and-gold-certificate-of-appreciation/",
        copyOfNationalId: "https://www.canva.com/p/templates/EAFh7cFx9So-white-and-gold-certificate-of-appreciation/",
        loanStatus: "Approved",
    },
    {
        _id: "3",
        firstName: "Michael",
        lastName: "Johnson",
        nationalId: "3234567890123456",
        email: "michael.johnson@example.com",
        teacherId: "T1003",
        phone: "0712345680",
        dateOfBirth: new Date("1975-02-10"),
        gender: "Male",
        maritalStatus: "Divorced",
        numberOfDependencies: 1,
        workSchool: "Riverdale High",
        position: "Science Teacher",
        monthlySalary: 3200,
        amountRequested: 10000,
        repaymentReriod: 12,
        bankAccountNumber: "3234567890",
        proofOffEmployment: "https://www.canva.com/p/templates/EAFh7cFx9So-white-and-gold-certificate-of-appreciation/",
        copyOfNationalId: "https://www.canva.com/p/templates/EAFh7cFx9So-white-and-gold-certificate-of-appreciation/",
        loanStatus: "Rejected",
    },
    {
        _id: "4",
        firstName: "Emily",
        lastName: "Davis",
        nationalId: "4234567890123456",
        email: "emily.davis@example.com",
        teacherId: "T1004",
        phone: "0712345681",
        dateOfBirth: new Date("1990-07-30"),
        gender: "Female",
        maritalStatus: "Widowed",
        numberOfDependencies: 3,
        workSchool: "Sunset Elementary",
        position: "History Teacher",
        monthlySalary: 2900,
        amountRequested: 16000,
        repaymentReriod: 30,
        bankAccountNumber: "4234567890",
        proofOffEmployment: "https://www.canva.com/p/templates/EAFh7cFx9So-white-and-gold-certificate-of-appreciation/",
        copyOfNationalId: "https://www.canva.com/p/templates/EAFh7cFx9So-white-and-gold-certificate-of-appreciation/",
        loanStatus: "Update required",
    },
    {
        _id: "5",
        firstName: "Robert",
        lastName: "Brown",
        nationalId: "5234567890123456",
        email: "robert.brown@example.com",
        teacherId: "T1005",
        phone: "0712345682",
        dateOfBirth: new Date("1982-03-25"),
        gender: "Male",
        maritalStatus: "Married",
        numberOfDependencies: 4,
        workSchool: "Maplewood High",
        position: "Physics Teacher",
        monthlySalary: 3100,
        amountRequested: 14000,
        repaymentReriod: 20,
        bankAccountNumber: "5234567890",
        proofOffEmployment: "https://www.canva.com/p/templates/EAFh7cFx9So-white-and-gold-certificate-of-appreciation/",
        copyOfNationalId: "https://www.canva.com/p/templates/EAFh7cFx9So-white-and-gold-certificate-of-appreciation/",
        loanStatus: "Pending",
    },
    {
        _id: "6",
        firstName: "Linda",
        lastName: "Miller",
        nationalId: "6234567890123456",
        email: "linda.miller@example.com",
        teacherId: "T1006",
        phone: "0712345683",
        dateOfBirth: new Date("1978-09-18"),
        gender: "Female",
        maritalStatus: "Single",
        numberOfDependencies: 0,
        workSchool: "Oakridge School",
        position: "Chemistry Teacher",
        monthlySalary: 3300,
        amountRequested: 18000,
        repaymentReriod: 36,
        bankAccountNumber: "6234567890",
        proofOffEmployment: "https://www.canva.com/p/templates/EAFh7cFx9So-white-and-gold-certificate-of-appreciation/",
        copyOfNationalId: "https://www.canva.com/p/templates/EAFh7cFx9So-white-and-gold-certificate-of-appreciation/",
        loanStatus: "Approved",
    },
    {
        _id: "7",
        firstName: "David",
        lastName: "Garcia",
        nationalId: "7234567890123456",
        email: "david.garcia@example.com",
        teacherId: "T1007",
        phone: "0712345684",
        dateOfBirth: new Date("1983-12-10"),
        gender: "Male",
        maritalStatus: "Married",
        numberOfDependencies: 2,
        workSchool: "Lakeview High",
        position: "Geography Teacher",
        monthlySalary: 3050,
        amountRequested: 13000,
        repaymentReriod: 15,
        bankAccountNumber: "7234567890",
        proofOffEmployment: "https://www.canva.com/p/templates/EAFh7cFx9So-white-and-gold-certificate-of-appreciation/",
        copyOfNationalId: "https://www.canva.com/p/templates/EAFh7cFx9So-white-and-gold-certificate-of-appreciation/",
        loanStatus: "Rejected",
    },
    {
        _id: "8",
        firstName: "Barbara",
        lastName: "Martinez",
        nationalId: "8234567890123456",
        email: "barbara.martinez@example.com",
        teacherId: "T1008",
        phone: "0712345685",
        dateOfBirth: new Date("1979-04-22"),
        gender: "Female",
        maritalStatus: "Widowed",
        numberOfDependencies: 1,
        workSchool: "Cedarwood Elementary",
        position: "Art Teacher",
        monthlySalary: 2800,
        amountRequested: 12000,
        repaymentReriod: 10,
        bankAccountNumber: "8234567890",
        proofOffEmployment: "https://www.canva.com/p/templates/EAFh7cFx9So-white-and-gold-certificate-of-appreciation/",
        copyOfNationalId: "https://www.canva.com/p/templates/EAFh7cFx9So-white-and-gold-certificate-of-appreciation/",
        loanStatus: "Pending",
   
    }
];